### ISSUE TITLE
new layouts do not get noticed until sbt restart

### ISSUE THREAD

**Issue by mlc** [jberkel/android-plugin#100]
I'm using the `TypedResources` functionality in developing an application, and I noticed that while I leave an sbt console open, then the `generate-typed-resources` task (and tasks like `compile` that depend on it) will not notice new layout XML files. The workaround is to quit and restart sbt, but it actually took me some time to figure this out.

**Comment by jberkel** [comment]
any ideas @aslakjo ?

**Comment by aslakjo** [comment]
I am able to see the same issue on my project. Maybe we need to refresh some of the underlying structures. @mlc or any one, feel free to try out some solution if you like to. I hope to look into it over the christmas holidays.

**Comment by aslakjo** [comment]
It seems that both mainResPath and layoutPath was of type SettingKey which only is initialized at startup. I have changed both to TaskKey, which is updated for every use.

@mlc are you able to verify that my branch works for you? https://github.com/aslakjo/android-plugin/tree/fix_%23100

**Comment by mlc** [comment]
I'm far from being any sort of sbt expert, but @aslakjo's solution seems to work as far as I can tell.

Thanks!
