### ISSUE TITLE
How can I override the proguard version?

### ISSUE THREAD

**Issue by DaveGit** [jberkel/android-plugin#103]
sbt-android plugin uses default proguard 4.6, but jdk1.7 is supported from proguard 4.7beta1 and up.
I would like to set the plugin to work with version 4.7beta3.
How can I do that?

**Comment by jberkel** [comment]
you need to change the dependency in android-plugins `build.sbt` and do a `sbt publish-local`. however 4.7 has not been published on maven central (http://repo1.maven.org/maven2/net/sf/proguard/proguard-base/)

**Comment by DaveGit** [comment]
Okay thanks.

I don't know if this is part of the android-plugin or giter8 and if I should mention it here, but giter8 doesn't create  a build.sbt in the topdirectory.
Instead it creates build.scala and plugins.sbt in the project directory with most of the settings in build.scala.
I thought the idea of sbt was to use build.sbt for the most part in the top level directory, but I could be wrong or maybe the idea changed.

**Comment by jberkel** [comment]
the ideas change all the time, sbt is under constant development. i think we need a *.scala build (since there are 2 projects) and the `build.scala` can only live in `project/`
