### ISSUE TITLE
Search for .android / avd directory also in ANDROID_SDK_HOME (sdkPath)

### ISSUE THREAD

**Issue by DaveGit** [jberkel/android-plugin#106]
In Android.scala in 

```
  val installedAvds = (s: State) => { 
    val avds = (Path.userHome / ".android" / "avd" * "*.ini").get 

    Space ~> avds.map(f => token(f.base)) 
                 .reduceLeftOption(_ | _).getOrElse(token("none")) 
  } 
```

Is het possible to make a fall back to look also in the ANDROID_SDK_HOME (I think it is sdkPath)?
Because in windows the latest android sdk make the .android below that directory.
Now I can only make an avd with the name "none".

**Comment by jberkel** [comment]
@DaveGit can you check if this works for you?

**Comment by DaveGit** [comment]
Yes, thanks. The avds are all listed now and I can start a created avd with the name for instance "Android-1.6"
