### ISSUE TITLE
Proguard making normal testing flow impossible.

### ISSUE THREAD

**Issue by lolsborn** [jberkel/android-plugin#11]
We're trying to work with Android/SBT in a test driven way and it is biting us.  Right now if you:
1. write a method called _foo_ that's not referenced else where in your Android project.
2. write a test for _foo_ code in your test project
3. run tests, notice failure due to _foo_ being removed by proguard and no longer existing.

I've tried adding various -keep options to proguardOption in my project, but haven't had any luck.  Any suggestions for a work around would be highly appreciated.

**Comment by jberkel** [comment]
i'm not sure if this is possible w/ proguard, but maybe something like

-keep class com.mypapp.\* 

where com.myapp is the application package name. we could even generate this automatically from the manifest.

**Comment by lolsborn** [comment]
Yeah, I tried adding that to proguardOption, but it didn't seem to help.  The class is being kept, but the 'unused' methods are getting removed.

**Comment by jberkel** [comment]
hmm then maybe -keep class com.myapp.* { public protected *; }  ?

**Comment by lolsborn** [comment]
That might have done the trick, at least it seems to for now.  I'll let you know.

**Comment by lolsborn** [comment]
This seems to work.  I think it would be desirable for anyone writing tests.  I just added it to proguardOption in my project, but it might be a good idea to roll this in to the plugin.  What do you think?

**Comment by jberkel** [comment]
yes that sounds like a good solution - main reason for proguard to run is to strip out unwanted scala library code, not your app code. maybe we can get this in as last change before releasing 0.4.2?

**Comment by jberkel** [comment]
Keep all application classes (closed by 36b70672e107b3f7075b9b81549f2c0fcb2f71fb)
