### ISSUE TITLE
If apache http classes are referenced, they should be stripped in proguard

### ISSUE THREAD

**Issue by geeksville** [jberkel/android-plugin#111]
Because the android runtime includes classes with the same names (and likely same functionality).  Here's the way I fixed it for just my project:

(from my SBT Build.scala)

   // The following packages should be excluded from android builds
    proguardExclude in Android <<= (proguardExclude in Android, fullClasspath in Runtime) map { (inherited, cp_) =>
      val cp: PathFinder = cp_.files
      val excluded =
        (cp *\* "httpclient-_.jar") +++
        (cp *_ "httpcore-_.jar") +++
        (cp *_ "commons-logging-_.jar") +++
        (cp *_ "commons-io-*.jar") get

```
  inherited ++ excluded
}
```

**Comment by jberkel** [comment]
i think this is fixed in jberkel/android-plugin@fac626c20, please verify. you should not need any special excludes anymore.

**Comment by geeksville** [comment]
Thanks Jan - it will be a couple of weeks before I can try it, but I'll let you know.

**Comment by jberkel** [comment]
ok, i'll close it for now, reopen if there are still problems
