### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by synic** [jberkel/android-plugin#119]
I can't get my latest project to resolve.  It started with just this error:

[error] SERVER ERROR: Bad Gateway url=http://nexus.scala-tools.org/content/repositories/snapshots/org/scala-tools/sbt/sbt-android-plugin/0.6.1-SNAPSHOT/maven-metadata.xml
[error] SERVER ERROR: Bad Gateway url=http://nexus.scala-tools.org/content/repositories/snapshots/org/scala-tools/sbt/sbt-android-plugin_2.9.1_0.11.2/0.6.1-SNAPSHOT/sbt-android-plugin-0.6.1-SNAPSHOT.pom

So, I closed the android-plugin code, and used sbt publish-local.

Now I'm getting the following errors:

[error] , unknown tag modelVersion in file:/home/synic/.ivy2/cache/scala_2.9.1/sbt_0.11.2/org.scala-tools.sbt/sbt-android-plugin/ivy-0.6.1-SNAPSHOT.xml.original
[error] , unknown tag groupId in file:/home/synic/.ivy2/cache/scala_2.9.1/sbt_0.11.2/org.scala-tools.sbt/sbt-android-plugin/ivy-0.6.1-SNAPSHOT.xml.original
[error] , unknown tag artifactId in file:/home/synic/.ivy2/cache/scala_2.9.1/sbt_0.11.2/org.scala-tools.sbt/sbt-android-plugin/ivy-0.6.1-SNAPSHOT.xml.original
[error] , unknown tag packaging in file:/home/synic/.ivy2/cache/scala_2.9.1/sbt_0.11.2/org.scala-tools.sbt/sbt-android-plugin/ivy-0.6.1-SNAPSHOT.xml.original
[error] , unknown tag description in file:/home/synic/.ivy2/cache/scala_2.9.1/sbt_0.11.2/org.scala-tools.sbt/sbt-android-plugin/ivy-0.6.1-SNAPSHOT.xml.original
[error] , unknown tag version in file:/home/synic/.ivy2/cache/scala_2.9.1/sbt_0.11.2/org.scala-tools.sbt/sbt-android-plugin/ivy-0.6.1-SNAPSHOT.xml.original

What am I doing wrong?

**Comment by Mononofu** [comment]
I had the same issue, solved it with the help of #scala.

Bascially, just checkout the plugin yourself and publish it locally with "sbt publish-local"
If you get errors when using the plugin, delete .ivy2 and try again.

To the maintainers: I was told to point you to http://www.scala-sbt.org/community-plugins.html#communityrepo

many thanks to retronym, who helped me solve the problem :)

**Comment by jberkel** [comment]
yes i need to move the stuff to the new repo. it's in progress...

**Comment by jberkel** [comment]
plugin is now hosted on scalasbt.artifactoryonline.com:

change your _project/plugins.sbt_ to:

```
resolvers += Resolver.url("scalasbt snapshots", new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-snapshots"))(Resolver.ivyStylePatterns)

addSbtPlugin("org.scala-sbt" % "sbt-android-plugin" % "0.6.1-SNAPSHOT" changing())
```

**Comment by synic** [comment]
Much better, thank you :)
