### ISSUE TITLE
aapt-generate reports success even when aapt fails

### ISSUE THREAD

**Issue by pimlott** [jberkel/android-plugin#125]
In one of my builds, the aapt-generate step reports:

```
.../src/main/res/layout/main.xml:19: error: Error: No resource found that matches the given name (at 'hint' with value '@string/amount').
[success] Total time: 0 s, completed Mar 27, 2012 12:53:46 PM
```

This should not be considered successs.  I verified by running it directly that aapt returns a non-zero exit status.  sbt-android-plugin doesn't seem to be checking this.

**Comment by jberkel** [comment]
which version of the plugin / sdk do you use? the most recent version has an error check, an other possibility could be that your version of aapt doesn't return correct exit codes. sometimes android tools are buggy.

**Comment by jberkel** [comment]
sorry, you're correct, i checked the wrong task. will fix.
