### ISSUE TITLE
Adding local jar

### ISSUE THREAD

**Issue by mads-hartmann** [jberkel/android-plugin#139]
Hi, 

Is it possible to add a local jar dependency to an android project such that it gets copied into the apk file? I want to add the jar file produced by a sub-project to the final apk. file. 

The issue seems to be related to #58 but adding 

```
proguardInJars in Android += file("...")
```

Doesn't seem to fix the problem. I still get `java.lang.NoClassDefFoundError: com.sidewayscoding.TextService`. The project is on github [here](http://github.com/mads379/android-scala-java-example)

Thanks,
Mads Hartmann Jensen

**Comment by lyricallogical** [comment]
Try this

``` scala
  lazy val fullAndroidSettings =
    settings ++ 
    AndroidProject.androidSettings ++
    AndroidMarketPublish.settings ++
    PlainJavaProject.settings ++ 
    Seq (autoScalaLibrary := true, useProguard in Android := true)
```

In multi project, PlainJavaProject.settings is fragile.

**Comment by mads-hartmann** [comment]
it works! Thanks a lot!
