### ISSUE TITLE
TypedView trait ineffective

### ISSUE THREAD

**Issue by ghost** [jberkel/android-plugin#15]
I noticed this in my code after 0.5.0 went out, the TypedView trait didn't extend TypedViewHolder. Not a big deal since this is probably the least common way to achieve the functionality, and you can still call the method against any by importing the implicit conversion.

Already fixed in master, just documenting the bug here.

**Comment by ghost** [comment]
Fixed in commit
042835cd8beac333e83e9985a00abe093793880c

**Comment by n8han** [comment]
By the way, that was me opening and commenting. Damn multiple accounts.
