### ISSUE TITLE
Why does each project get its own copy of scala compiler and library

### ISSUE THREAD

**Issue by babusri** [jberkel/android-plugin#16]
I have created several projects with script/create_project. When I run a command 'sbt update' (or even clean) the first thing it does to to get the scala compiler and then the library. And this takes quite a bit of time. Shouldn't this be done only if the compiler is not present.

downloading http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.7.7/scala-compiler-2.7.7.jar
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.7.7/scala-library-2.7.7.jar ...

**Comment by jberkel** [comment]
that's just the way sbt works - it makes it possible to build the project for different versions of scala.

however the jar files should get cached on your system, so it'll only be slow the first time the file gets downloaded.

if it doesn't get cached you might have permission problems, check the logs.
