### ISSUE TITLE
Problem hacking on the plugin

### ISSUE THREAD

**Issue by jimfulton** [jberkel/android-plugin#174]
I'm trying to use a local snapshot to debug some plugin behavior I don't understand.

If I create a snapshot from the current master, and try to use it, imports like:

```
import AndroidKeys._
```

fail:

```
[error] /Users/jim/t/android-scala/zebrareach/project/Build.scala:4: not found: object AndroidKeys
[error] import AndroidKeys._
[error]        ^
[error] one error found
```

Doing full imports like:

```
import org.scalasbt.androidplugin.AndroidKeys._
```

Seem to work.

If I create a snapshot from the 0.6.2 tag or from appamatto/android-plugin master, I don't get this error.

**Comment by appamatto** [comment]
Package names were added a few days ago: https://github.com/jberkel/android-plugin/commit/94fcea4092e66a55fd027b63f9c3ec1a375336f8

**Comment by jimfulton** [comment]
OK, I interpret that to mean that this is the new behavior is desired.

**Comment by appamatto** [comment]
I think so, at least it doesn't make sense to keep things in the default package.

**Comment by jimfulton** [comment]
That's cleaner, but of course, it will break existing builds. <shrug>

**Comment by jberkel** [comment]
true, but the change has been done on a snapshot version, so breaking behaviour is to be expected.

**Comment by jimfulton** [comment]
Sorry, not sure what you mean.  Maybe I don't know what you mean by "snapshot".  Are you suggesting that the next normal release won't require long imports? Or that I should expect breaking behavior with a 0 (.6.2) release?

I don't really care myself, as I'm working on my first build. I think a fair number of people are using this plugin, fwiw.
