### ISSUE TITLE
Issues with TypedResouces

### ISSUE THREAD

**Issue by lolsborn** [jberkel/android-plugin#18]
**See:** http://gist.github.com/543295

There are two separate issues here.
1. The import issue.  I'm using _root_.com.android everywhere with no issues, but honestly I'm not sure what would cause errors like this, it seems like there would have to be something else in my class path.
2. The _R.id.android:list issue_.  This looks like a bug.  I'm think one solution would be to just ignore R.id.android*, but list might be the only special case.

I'll put together a patch soon and see how things go.

**Comment by n8han** [comment]
Have you run "update" in the project?

**Comment by lolsborn** [comment]
I'm running 0.5.0.

I noticed the first issue was addressed already in http://github.com/adler24/android-plugin/commit/a2a64cc0d4b86b01abe3225ff8867413191232a7

I'm not sure if the second issue has been addressed.  I'll check out tip and see what happens.

**Comment by jberkel** [comment]
still issues with this?

**Comment by lolsborn** [comment]
I'm sorry, I'm no longer working on an Android/Scala project and am not really in a place where I can verify this issue.  Feel free to close it as "can not reproduce" if that's the case.  Unfortunately I'm not in a position to be much help :-(
