### ISSUE TITLE
0.7 SNAPSHOT, ProGuard: include native method names by default

### ISSUE THREAD

**Issue by stanch** [jberkel/android-plugin#182]
Hi,

I suggest that

```
"-keepclasseswithmembers class * { native <methods>; }"
```

is added to the default ProGuard configuration so that native methods work.
For motivation, see [1] and [2]. I am not sure if the renaming of this option, suggested in [2], is legit, but apparently it worked for me and solved `java.lang.NoSuchMethodError`s. We can add both anyway.

[1] http://proguard.sourceforge.net/index.html#manual/examples.html, section 16
[2] http://stackoverflow.com/questions/8613098/obsolete-proguard-file-use-keepclasseswithmembers-instead-of-keepclasseswithm

Kind regards,
Nick

**Comment by stanch** [comment]
P.S. If not in the default configuration, this line could be added to the [cookbook](http://fxthomas.github.io/android-plugin/tutorial/annex-b-cookbook.html) that @fxthomas is preparing in his fork.

**Comment by fxthomas** [comment]
Good point, thanks! Are you actually using that in an app?

**Comment by stanch** [comment]
@fxthomas, yes, I am using it. Sometimes I wish for “ProGuard” recipes that would come with each dependency I use, like !sources or !javadoc, so there is no guessing and log digging involved. Actually I have a weird idea about this, will post in the group.

**Comment by appamatto** [comment]
Since this doesn't handle callbacks made from native code to Java/Scala methods, I usually find it necessary to -keep the entire Scala class that contains the native methods and callbacks anyway.

**Comment by appamatto** [comment]
It looks like this got resolved in the Google Group, so closing.
