### ISSUE TITLE
Is this still in use/maintained?

### ISSUE THREAD

**Issue by christopherperry** [jberkel/android-plugin#202]
I tried to use this, and there were a bunch of issues getting set up. Changes in the way SBT packages things make it so it can't find the plugin.

I was able to successfully get set up with the [gradle-android-scala-plugin](https://github.com/saturday06/gradle-android-scala-plugin), but it doesn't seem to work in IntelliJ, you have to use Android Studio. Also, since it's not an SBT project with that plugin the IDE isn't as helpful, so working is a bit more of a pain that I would like.

**Comment by jberkel** [comment]
I don't use and maintain this anymore, sorry. See the README. There's https://github.com/pfn/android-sdk-plugin which is actively being developed at the moment.
