### ISSUE TITLE
Proguard is not using the build version of the scala library

### ISSUE THREAD

**Issue by weihsiu** [jberkel/android-plugin#3]
I am the guy who wrote the original AndroidProject.  Thanks for a job well done!

I am using xsbt 0.6.10 with android-plugin and encountered an issue when building against scala-2.8.0.Beta1-RC7.  Because xsbt is compiled in scala-2.7.7 but builds using scala-2.8.0, the injars parameter in the proguard task should include 2.8.0 scala-library instead of 2.7.7.

Below is the my patch:
diff --git a/src/main/scala/AndroidProject.scala b/src/main/scala/AndroidProject.scala
index 493c37c..40d587a 100644
--- a/src/main/scala/AndroidProject.scala
+++ b/src/main/scala/AndroidProject.scala
@@ -114,7 +114,7 @@ abstract class AndroidProject(info: ProjectInfo) extends DefaultProject(info) {
   def proguardAction = proguardTask dependsOn(compile) describedAs("Optimize class files.")
   def proguardTask = task { 
     val args = "-injars" ::  mainCompilePath.absolutePath+File.pathSeparator+
-                             FileUtilities.scalaLibraryJar.getAbsolutePath+"(!META-INF/MANIFEST.MF,!library.properties)"+
-                             buildScalaInstance.libraryJar.getAbsolutePath+"(!META-INF/MANIFEST.MF,!library.properties)"+
                            (if (!proguardInJars.getPaths.isEmpty) File.pathSeparator+proguardInJars.getPaths.map(_+"(!META-INF/MANIFEST.MF)").mkString(File.pathSeparator) else "") ::  
              "-outjars" :: classesMinJarPath.absolutePath ::
              "-libraryjars" :: libraryJarPath.getPaths.mkString(File.pathSeparator) ::

**Comment by jberkel** [comment]
I tried to apply your patch but the plugin doesn't compile anymore (using sbt 0.5.6, AndroidProject.scala:117: not found: value buildScalaInstance).

does your patch assume xsbt is used ?

**Comment by weihsiu** [comment]
unfortunately yes, buildScalaInstance is only available in xsbt.

**Comment by jberkel** [comment]
i've been meaning to try out xsbt anyway. i guess i'll apply your patch in a separate branch. xsbt will supersede sbt at some point, if i understand correctly?

**Comment by weihsiu** [comment]
yes, i think the new 0.6.12 version of xsbt is becoming the official 0.7 beta.
http://groups.google.com/group/simple-build-tool/browse_thread/thread/0cd3fd1ab6b14601

**Comment by jberkel** [comment]
nathan has added a hook for the scala library path (see latest commit). problem is that projects overriding it for use with xsbt will ony work with xsbt. another option would be to use reflection to dynamically adapt the path?

**Comment by jberkel** [comment]
version 0.4 supports sbt 0.5.6 and xsbt.
