### ISSUE TITLE
Change sbt-android-plugin version to 0.5.1 in create_project script

### ISSUE THREAD

**Issue by rupertbates** [jberkel/android-plugin#30]
The line:

val android = "org.scala-tools.sbt" % "sbt-android-plugin" % "0.5.0"

in the file android-plugin\script\create_project

Should be updated to version 0.5.1 as this is the current version

**Comment by jberkel** [comment]
0.5.1

  Closed by e7acf15c5f424e8f67f2c0a193d754b0c63c3238
