### ISSUE TITLE
THIS TOOL IS DEPRECATED.

### ISSUE THREAD

**Issue by danielribeiro** [jberkel/android-plugin#44]
It gives me "THIS TOOL IS DEPRECATED. See --help for more information" when using sbt start-emulator. Stats:

```
robospecs_example $ sbt 
[info] Building project RobospecsExample 0.1 against Scala 2.8.1
[info]    using RobospecsExample with sbt 0.7.4 and Scala 2.7.7
```

**Comment by jberkel** [comment]
the version in master fixed this already. 0.5.2 should be released soon (in the meantime do a checkout and `sbt update publish-local`)

**Comment by danielribeiro** [comment]
Well, did not really work:

```
    [warn] Credentials file /home/daniel/.ivy2/.credentials does not exist
    [info] Building project sbt-android-plugin 0.5.2-SNAPSHOT against Scala 2.7.7
    [info]    using AndroidPlugin with sbt 0.7.4 and Scala 2.7.7
    [info] 
    [info] == compile ==
    [info]   Source analysis: 11 new/modified, 0 indirectly invalidated, 0 removed.
    [info] Compiling main sources...
    [error] /home/daniel/IdeaProjects/andtest/andj/android-plugin/src/main/scala/BaseAndroidProject.scala:1: not found: value proguard
    [error] import proguard.{Configuration=>ProGuardConfiguration, ProGuard, ConfigurationParser}
```

(....)

Guess I'll try to use it on eclipse for the time being: http://www.assembla.com/wiki/show/scala-ide/Developing_for_Android

**Comment by jberkel** [comment]
you need to run `sbt update` first.
also the line "THIS TOOL IS DEPRECATED." is just a warning, not an error - you can ignore it.

**Comment by danielribeiro** [comment]
It seems "this tool is deprecated" prevents the emulator from starting. If not, something else is....

**Comment by jberkel** [comment]
"prevent emulator from starting" ? the plugin doesn't start the emulator?

**Comment by danielribeiro** [comment]
Sorry it wasn't focused: ... when using _sbt start-emulator_ ...

It not only gives Deprecated tool erros, it will not start it.

**Comment by fabianpage** [comment]
the command "sbt start-emulator" starts your app in an already running android emulator. So you have first to start the emulator and then "sbt start-emulator".

**Comment by danielribeiro** [comment]
I'll test it again. For the time being, a minor tweek on [HelloScalaOnAndroid project](https://github.com/danielribeiro/HelloScalaOnAndroid) + Ant (even though I really prefer SBT) did the magic for me. I'll probably write a small article summing up the whole adventure of gettign scala + android work, along with both Eclipe and IDEA support.
