### ISSUE TITLE
README bug with setup

### ISSUE THREAD

**Issue by truedat101** [jberkel/android-plugin#49]
change setup line https://github.com/n8han/conscript/raw/master/setup.sh to

https://raw.github.com/n8han/conscript/master/setup.sh

github must have changed the way they expose raw.

**Comment by jberkel** [comment]
thanks - next time please consider just changing it and submit a pull request along with the bug report.

**Comment by n8han** [comment]
Both URLs work for me.

**Comment by jberkel** [comment]
yes, but one is a redirect - unless you tell curl to autofollow you just get the redirect html body in the file

**Comment by n8han** [comment]
Oh, thanks then I will update my other docs as well.
