### ISSUE TITLE
building error with gr8 template

### ISSUE THREAD

**Issue by iNoles** [jberkel/android-plugin#55]
When I created a project with gr8 template and up-to-date master branch, I get

[error] missing arguments for method ++ in trait TraversableLike;
[error] follow this method with `_' if you want to treat it as a partially applied function
[error]     TypedResources.settings ++

in build.scala

**Comment by philcali** [comment]
This can happen if you are using sbt 0.11.x series when the plugin was built on top of the 0.10.x series. 

Are you using sbt 0.10.x or sbt 0.11.0.RC0?

**Comment by iNoles** [comment]
I believe it was sbt 0.10
