### ISSUE TITLE
PlainJavaProject.settings doesn't actually override manifestPath

### ISSUE THREAD

**Issue by appamatto** [jberkel/android-plugin#59]
Using:

```
 settings = General.fullAndroidSettings ++ PlainJavaProject.settings
```

where fullAndroidSettings includes AndroidProject.androidSettings causes sbt to look for AndroidManifest.xml in src/main instead of baseDirectory.

I've tried adding manifestPath := file("AndroidManifest.xml") in various places but to no avail.

**Comment by jberkel** [comment]
i'm currently rewriting the manifest related code - this should be fixed soon.

**Comment by samueltardieu** [comment]
Great, I got hit by the same problem today while playing with sbt in a Java-only project.

**Comment by jberkel** [comment]
can you try the refactor-manifest branch ? it should work there - i changed the manifestpath from a setting to a task so that AndroidManifestGenerator can be plugged in more easily.

however the branch requires sbt 0.11.1-SNAPSHOT.

**Comment by appamatto** [comment]
I just tested this and it's working for my project.

**Comment by jberkel** [comment]
thanks for the feedback!
