### ISSUE TITLE
useProguard = false in version 0.60 and sbt 0.11 ?

### ISSUE THREAD

**Issue by weiju** [jberkel/android-plugin#65]
Hi, 
I was wondering how one would  go about to set useProguard to false in V 0.60 and sbt 0.11 ? I noticed the default is true in AndroidBase, but my attempts to override it were all unsuccessful (other than setting the value directly and repackaging the plugin).

Thanks

**Comment by jberkel** [comment]
it needs to be scoped:

`useProguard in Android := false`

**Comment by weiju** [comment]
Hi,

thanks for your reply. I actually tried that, with the setup below, based on a giter8-generated project. However this has no effect, the Proguard phase is executed (while I would have expected "Skipping Proguard"). 
In addition I also tried

val main = Project("MyProject", file("."), settings = General.fullAndroidSettings) settings(/\* including settings with useProguard here */)

which did not have an effect either.

Best,

Wei-ju
===== SBT full configuration build.scala ====
import sbt._

import Keys._
import AndroidKeys._

object General {
  val settings = Defaults.defaultSettings ++ Seq (
    name := "MyProject",
    version := "0.1",
    scalaVersion := "2.9.1",
    platformName in Android := "android-10",
    useProguard in Android := true
  )

  lazy val fullAndroidSettings =
    General.settings ++
    AndroidProject.androidSettings ++
    TypedResources.settings ++
    AndroidMarketPublish.settings ++ Seq (
      keyalias in Android := "change-me",
      libraryDependencies += "org.scalatest" %% "scalatest" % "1.6.1" % "test"
    )
}

object AndroidBuild extends Build {

  lazy val main = Project (
    "MyProject",
    file("."),
    settings = General.fullAndroidSettings
  )

  lazy val tests = Project (
    "tests",
    file("tests"),
    settings = General.settings ++ AndroidTest.androidSettings
  ) dependsOn main
}

**Comment by jberkel** [comment]
it's probably an ordering issue. try setting useProguard after you add AndroidProject.androidSettings.

**Comment by weiju** [comment]
Setting it like below still invokes Proguard...

...
  lazy val fullAndroidSettings =
    General.settings ++
    AndroidProject.androidSettings ++
    TypedResources.settings ++
    AndroidMarketPublish.settings ++ Seq (
      keyalias in Android := "change-me",
      libraryDependencies += "org.scalatest" %% "scalatest" % "1.6.1" % "test"
    ) ++ Seq(
      useProguard in Android := true
    )
....

**Comment by jberkel** [comment]
shouldn't it be

```
useProguard in Android := false
```

?

**Comment by weiju** [comment]
'tschuldigung, mein Fehler..

you are right, it works.

Thanks a lot !
