### ISSUE TITLE
Class Not Found Error when using intent Receiver

### ISSUE THREAD

**Issue by lolsborn** [jberkel/android-plugin#7]
When I build everything with Ant and http://code.google.com/p/scalaforandroid/ everything works fine, but when I build my project with sbt/android-plugin Android throws an exception on boot when looking for my BroadcastReceiver subclass. Launching the app through the main activity still works fine, just this broadcast receiver class is not found.

My BroadcastReceiver is simple:

```
class CoreReceiver extends BroadcastReceiver {
  val BOOT_COMPLETED = "android.intent.action.BOOT_COMPLETED"

  override def onReceive(context: Context, intent: Intent) {
     if (intent.getAction().equals(BOOT_COMPLETED)) {
       // Do something
    }
  }
}
```

and I have the following in my AndroidManifest:

```
  <receiver android:name="CoreReceiver">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
    </intent-filter>
  </receiver>
```

**Comment by jberkel** [comment]
closed in 1118d587a7a5af03a3f4
