### ISSUE TITLE
Java+Scala Project: Object app is not a member of package

### ISSUE THREAD

**Issue by glenviewjeff** [jberkel/android-plugin#70]
I successfully built the Scala-only project template. Next, I tried to add some Java sources to my project and got the following error in TR.scala.

Any ideas what could be the cause? (it seems to me like sbt can't find the Android libraries now that I added Java sources for some reason.)

[info] Compiling 2 Scala sources and 5 Java sources to D:\Workspaces\MyProject\my-project\target\scala-2.9.0-1\classes...
[error] D:\Workspaces\MyProject\my-project\target\src_managed\main\scala\com\mydomain\myproject\TR.scala:2: object app is not a member of package com.mydomain.myproject.android
[error] import android.app.Activity
[error]                ^
[error] D:\Workspaces\MyProject\my-project\target\src_managed\main\scala\com\mydomain\myproject\TR.scala:3: object view is not a member of package com.mydomain.myproject.android
[error] import android.view.View
[error]                ^
[error] two errors found
[error] {file:/D:/Workspaces/MyProject/my-project/}My Project/compile:compile: Compilation failed
[error] Total time: 5 s, completed Oct 12, 2011 11:20:55 AM

**Comment by glenviewjeff** [comment]
Thanks to Yifan Yu's response in Google Groups, this appears to be a bug.

"You have a package path named com.mydomain.myproject.android, so it's confusing the compiler when it tries to compile TR.scala in 'com.mydomain.myproject', because it thinks of 'android.whatever' as a relative path. The plugin tries to prepend _root_. to the Activity source it generates, but it forgets to do so for TR.scala."

As suggested, renaming the package path to com.mydomain.myproject.androidstuff fixed the problem.

**Comment by jberkel** [comment]
fixed in jberkel/android-plugin@2275b2e

**Comment by glenviewjeff** [comment]
Thanks Jan!
