### ISSUE TITLE
ProGuard ignores libraries in lib folder 

### ISSUE THREAD

**Issue by migo** [jberkel/android-plugin#77]
I use one library that is not available via Maven, so I put it in the lib folder of my project.
Compilation of the class files seems to work this way, but the library is apparently not picked up by ProGuard during the compression phase.
When running the application on the phone, consequently, I get an exception saying that a class contained in the library could not be found.

Is there a way to specify that jars in the lib folder should be picked up by ProGuard?

Thanks!

PS: I use sbt 0.11 and the sbt_011 of the android-plugin.

**Comment by migo** [comment]
I found a discussion about this problem here:
http://groups.google.com/group/scala-on-android/browse_thread/thread/2219fc6b6b17690c

The solution suggested there works (setting the option "proguardInJars in Android ++= ((file("lib") *\* "*.jar") get)"),
but I still think this should be default behavior.

**Comment by jberkel** [comment]
weird, just tested this and jar files in `lib` turn up in the proguard injars config. can you double check with 

```
set logLevel := Level.Debug
```

?

or maybe something else is needed in addition to `-injars`

**Comment by migo** [comment]
Yes, you are right, sorry.

My version of the android-plugin was about one month old. I updated and now it works; it must have been fixed in the meantime.
I close the bug.
