### ISSUE TITLE
Correct README.markdown

### ISSUE THREAD

**Issue by nightscape** [jberkel/android-plugin#8]
In the README.markdown it should read
        import sbt._
        class Plugins(info: ProjectInfo) extends PluginDefinition(info) {
            val android = "org.scala-tools.sbt" % "sbt-android-plugin" % "0.4.1"
        }
instead of
        import sbt._
        class Plugins(info: ProjectInfo) extends PluginDefinition(info) {
            val android = "org.scala-tools.sbt" % "android-plugin" % "0.4.1"
        }

**Comment by jberkel** [comment]
0.4.2 will have renamed package id
