### ISSUE TITLE
Problems with custom Android version

### ISSUE THREAD

**Issue by choedl** [jberkel/android-plugin#83]
We are using a customized Android version where the version
information is not an Int.

This is our AndroidManifest.xml:

```
[...]
  android:versionCode="1"
  android:versionName="1.0">
 <uses-sdk android:minSdkVersion="customized" />
[...]
```

In this case we get the following error when starting sbt:
java.lang.NumberFormatException: For input string: "customized"

Unfortunately it is not in our hand to change the version Information
to an Int. Is it possible to use such a customized version with the
sbt android plugin? 

We are using version 0.6.0-SNAPSHOT.

**Comment by jberkel** [comment]
i guess it could be made to work, but it's a weird edge case, since the specification explictly requires an integer value in there:

http://developer.android.com/guide/topics/manifest/uses-sdk-element.html

**Comment by choedl** [comment]
Ok. Didn't know about that.
