### ISSUE TITLE
Latest sbt-android-plugin build fails with "value storeAs is not a member of sbt.Project.Initialize[sbt.Task[String]]"

### ISSUE THREAD

**Issue by glenviewjeff** [jberkel/android-plugin#87]
See log:

[/usr/local]$ git clone git://github.com/jberkel/android-plugin.git
Cloning into android-plugin...
remote: Counting objects: 2015, done.
remote: Compressing objects: 100% (616/616), done.
remote: Total 2015 (delta 1006), reused 1908 (delta 915)
Receiving objects: 100% (2015/2015), 230.93 KiB | 289 KiB/s, done.
Resolving deltas: 100% (1006/1006), done.
[/usr/local]$ cd android-plugin
[...local/android-plugin]$ sbt publish-local
[info] Set current project to sbt-android-plugin (in build file:/C:/cygwin/usr/local/android-plugin/)
[warn] Credentials file C:\Users\Jeff.ivy2.credentials does not exist
[info] Packaging C:\cygwin\usr\local\android-plugin\target\scala-2.9.1\sbt-0.11.0\sbt-android-plugin-0.6.0-sources.jar ...
[info] Done packaging.
[info] Updating {file:/C:/cygwin/usr/local/android-plugin/}default-a93f88...
[info] Wrote C:\cygwin\usr\local\android-plugin\target\scala-2.9.1\sbt-0.11.0\sbt-android-plugin-0.6.0.pom
[info] Done updating.
[info] :: delivering :: org.scala-tools.sbt#sbt-android-plugin;0.6.0 :: 0.6.0 :: release :: Wed Nov 16 11:14:54 CST 2011
[info]  delivering ivy file to C:\cygwin\usr\local\android-plugin\target\scala-2.9.1\sbt-0.11.0\ivy-0.6.0.xml
[info] Generating API documentation for main sources...
[info] Compiling 18 Scala sources to C:\cygwin\usr\local\android-plugin\target\scala-2.9.1\sbt-0.11.0\classes...
[error] C:\cygwin\usr\local\android-plugin\src\main\scala\AndroidBase.scala:63: value storeAs is not a member of sbt.Project.Initialize[sbt.Task[String]]
[error]     manifestPackageName <<= findPath storeAs manifestPackageName triggeredBy manifestPath,
[error]                                      ^
[error] C:\cygwin\usr\local\android-plugin\src\main\scala\AndroidBase.scala:63: value storeAs is not a member of sbt.Project.Initialize[sbt.Task[String]]
[error]     manifestPackageName <<= findPath storeAs manifestPackageName triggeredBy manifestPath,
[error]                                      ^
[error] C:\cygwin\usr\local\android-plugin\src\main\scala\AndroidDdm.scala:232: not found: value loadFromContext
[error]         threadListParser(s, loadFromContext(manifestPackageName, ctx, s) getOrElse "", path.absolutePath, true)))
[error]                             ^
[error] C:\cygwin\usr\local\android-plugin\src\main\scala\AndroidDdm.scala:237: not found: value loadFromContext
[error]         threadListParser(s, loadFromContext(manifestPackageName, ctx, s) getOrElse "", path.absolutePath, false)))
[error]                             ^
[error] C:\cygwin\usr\local\android-plugin\src\main\scala\AndroidDdm.scala:232: not found: value loadFromContext
[error]         threadListParser(s, loadFromContext(manifestPackageName, ctx, s) getOrElse "", path.absolutePath, true)))
[error]                             ^
[error] C:\cygwin\usr\local\android-plugin\src\main\scala\AndroidDdm.scala:237: not found: value loadFromContext
[error]         threadListParser(s, loadFromContext(manifestPackageName, ctx, s) getOrElse "", path.absolutePath, false)))
[error]                             ^
[error] three errors found
[info] No documentation generated with unsucessful compiler run
[error] three errors found
[error] {file:/C:/cygwin/usr/local/android-plugin/}default-a93f88/compile:doc: Scaladoc generation failed
[error] {file:/C:/cygwin/usr/local/android-plugin/}default-a93f88/compile:compile: Compilation failed
[error] Total time: 15 s, completed Nov 16, 2011 11:15:05 AM
[...local/android-plugin]$

**Comment by jberkel** [comment]
you'll need sbt 0.11.1

**Comment by glenviewjeff** [comment]
Thanks--built!
