### ISSUE TITLE
Problems with useProguard = false

### ISSUE THREAD

**Issue by th0br0** [jberkel/android-plugin#90]
Hey there,

first of all -- great plugin, love it!
As proguard really makes the package build step slo~w, I want to disable it.
However, if I set "useProguard := false", the application won't start anymore.

I tend to get errors alike "Link of class 'Lmy/application/MyApplication;' failed" normally in connection with a class "scala/ScalaObject" could not be found error.

How can I solve this issue? 

Cheers,

Andreas

**Comment by jberkel** [comment]
this is expected - if you skip the proguard step the scala libs won't get included. there are a few ways around that, see this thread on SO: http://stackoverflow.com/questions/7941178/long-build-times-with-sbt-android-plugin/

**Comment by th0br0** [comment]
Thanks a lot for the link; it'd be great if that could be added to the README or so as I didn't really find much information about disabling proguard...

**Comment by jberkel** [comment]
ok, will add the info
